return {
	filetypes = { "php" },
	root_markers = { "composer.json", ".git" },
	init_options = {
		licenceKey = vim.fn.expand("~/intelephense/licence.txt"), -- optional, for paid features
	},
	settings = {
		intelephense = {
			stubs = {
				"bcmath",
				"bz2",
				"calendar",
				"Core",
				"curl",
				"date",
				"dom",
				"fileinfo",
				"filter",
				"gd",
				"gettext",
				"hash",
				"iconv",
				"json",
				"libxml",
				"mbstring",
				"mcrypt",
				"mysql",
				"mysqli",
				"openssl",
				"pcntl",
				"pcre",
				"PDO",
				"pdo_mysql",
				"Phar",
				"readline",
				"regex",
				"session",
				"SimpleXML",
				"sockets",
				"sodium",
				"SPL",
				"standard",
				"tokenizer",
				"xml",
				"xmlreader",
				"xmlwriter",
				"zip",
				"zlib",
			},
			diagnostics = { enable = true },
			completion = { fullyQualifyGlobalConstantsAndFunctions = false },
		},
	},
}
